export const EXERCISE_LIBRARY = {
  'supino-reto': {
    name: 'Supino reto',
    slug: 'supino-reto',
    primaryMuscle: 'Peito',
    secondaryMuscles: ['Triceps', 'Ombros anteriores'],
    muscleGroups: ['Peito', 'Triceps', 'Ombros'],
    equipment: 'Banco e barra',
    level: 'Intermediario',
    shortInstruction: 'Desca a barra com controle ate a linha do peito e empurre mantendo escapulas estaveis.',
    commonMistakes: ['Quicar a barra no peito', 'Abrir demais os cotovelos', 'Tirar o quadril do banco'],
    safetyNote: 'Usar carga que permita controle total e, se pesado, pedir supervisao.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/supino-reto.gif',
  },
  'supino-inclinado-halteres': {
    name: 'Supino inclinado com halteres',
    slug: 'supino-inclinado-halteres',
    primaryMuscle: 'Peito superior',
    secondaryMuscles: ['Triceps', 'Ombros anteriores'],
    muscleGroups: ['Peito superior', 'Triceps', 'Ombros'],
    equipment: 'Banco inclinado e halteres',
    level: 'Intermediario',
    shortInstruction: 'Empurre os halteres acima do peito superior e desca ate sentir alongamento controlado.',
    commonMistakes: ['Bater halteres no topo', 'Arquear lombar em excesso', 'Descer sem controle'],
    safetyNote: 'Ajustar banco sem exagerar a inclinacao para nao sobrecarregar ombros.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/supino-inclinado-halteres.gif',
  },
  'flexao-bracos': {
    name: 'Flexao de bracos',
    slug: 'flexao-bracos',
    primaryMuscle: 'Peito',
    secondaryMuscles: ['Triceps', 'Ombros', 'Core'],
    muscleGroups: ['Peito', 'Triceps', 'Ombros', 'Core'],
    equipment: 'Peso corporal',
    level: 'Iniciante',
    shortInstruction: 'Mantenha o corpo alinhado, desca o peito em direcao ao solo e empurre ate estender os bracos.',
    commonMistakes: ['Quadril cair', 'Abrir cotovelos demais', 'Encurtar amplitude'],
    safetyNote: 'Adaptar com joelhos no solo se perder alinhamento.',
    mediaStatus: 'placeholder',
    gif: null,
    futureGifPath: '/exercises/gifs/flexao-bracos.gif',
  },
  'puxada-alta': {
    name: 'Puxada alta',
    slug: 'puxada-alta',
    primaryMuscle: 'Costas',
    secondaryMuscles: ['Biceps', 'Antebracos'],
    muscleGroups: ['Costas', 'Biceps', 'Antebracos'],
    equipment: 'Polia alta',
    level: 'Iniciante',
    shortInstruction: 'Puxe a barra em direcao ao alto do peito, mantendo tronco firme e ombros baixos.',
    commonMistakes: ['Puxar atras da nuca', 'Balancar o tronco', 'Elevar ombros'],
    safetyNote: 'Evitar puxada atras da nuca para reduzir estresse cervical e nos ombros.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/puxada-alta.gif',
  },
  'remada-curvada': {
    name: 'Remada curvada',
    slug: 'remada-curvada',
    primaryMuscle: 'Costas',
    secondaryMuscles: ['Biceps', 'Core', 'Posteriores'],
    muscleGroups: ['Costas', 'Biceps', 'Core'],
    equipment: 'Barra ou halteres',
    level: 'Intermediario',
    shortInstruction: 'Incline o tronco com coluna neutra e puxe a carga em direcao ao abdomen.',
    commonMistakes: ['Arredondar lombar', 'Usar impulso', 'Encolher ombros'],
    safetyNote: 'Reduzir carga se nao conseguir manter coluna neutra.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/remada-curvada.gif',
  },
  'remada-baixa': {
    name: 'Remada baixa',
    slug: 'remada-baixa',
    primaryMuscle: 'Costas',
    secondaryMuscles: ['Biceps', 'Romboides', 'Antebracos'],
    muscleGroups: ['Costas', 'Biceps', 'Romboides', 'Antebracos'],
    equipment: 'Polia baixa',
    level: 'Iniciante',
    shortInstruction: 'Puxe o cabo ate o abdomen, aproximando escapulas sem jogar o tronco para tras.',
    commonMistakes: ['Hiperestender lombar', 'Puxar com punhos', 'Perder controle na volta'],
    safetyNote: 'Manter peito aberto e retorno controlado para proteger lombar.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/remada-baixa.gif',
  },
  'levantamento-terra': {
    name: 'Levantamento terra',
    slug: 'levantamento-terra',
    primaryMuscle: 'Posterior de cadeia',
    secondaryMuscles: ['Gluteos', 'Costas', 'Core', 'Antebracos'],
    muscleGroups: ['Posterior de cadeia', 'Gluteos', 'Costas', 'Core'],
    equipment: 'Barra',
    level: 'Avancado',
    shortInstruction: 'Empurre o chao, suba a barra junto ao corpo e mantenha coluna neutra durante todo o movimento.',
    commonMistakes: ['Arredondar costas', 'Deixar barra longe do corpo', 'Puxar com os bracos'],
    safetyNote: 'Exigir tecnica validada antes de usar cargas altas.',
    mediaStatus: 'placeholder',
    gif: null,
    futureGifPath: '/exercises/gifs/levantamento-terra.gif',
  },
  'agachamento-livre': {
    name: 'Agachamento livre',
    slug: 'agachamento-livre',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Gluteos', 'Posteriores', 'Core'],
    muscleGroups: ['Quadriceps', 'Gluteos', 'Posteriores', 'Core'],
    equipment: 'Peso corporal ou barra',
    level: 'Intermediario',
    shortInstruction: 'Desca com quadril para tras e joelhos alinhados, depois suba empurrando o chao.',
    commonMistakes: ['Joelhos colapsarem', 'Tirar calcanhar do chao', 'Arredondar lombar'],
    safetyNote: 'Ajustar amplitude conforme mobilidade e manter carga controlada.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/agachamento-livre.gif',
  },
  'leg-press': {
    name: 'Leg press',
    slug: 'leg-press',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Gluteos', 'Posteriores'],
    muscleGroups: ['Quadriceps', 'Gluteos', 'Posteriores'],
    equipment: 'Maquina leg press',
    level: 'Iniciante',
    shortInstruction: 'Empurre a plataforma sem travar os joelhos e retorne com controle.',
    commonMistakes: ['Descer demais e tirar quadril do banco', 'Travar joelhos', 'Usar amplitude curta'],
    safetyNote: 'Manter lombar apoiada e evitar travamento completo dos joelhos.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/leg-press.gif',
  },
  'cadeira-extensora': {
    name: 'Cadeira extensora',
    slug: 'cadeira-extensora',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: [],
    muscleGroups: ['Quadriceps'],
    equipment: 'Maquina extensora',
    level: 'Iniciante',
    shortInstruction: 'Estenda os joelhos com controle e retorne sem deixar o peso bater.',
    commonMistakes: ['Impulsionar a carga', 'Subir rapido demais', 'Perder ajuste do eixo do joelho'],
    safetyNote: 'Ajustar o equipamento para alinhar eixo da maquina ao joelho.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/cadeira-extensora.gif',
  },
  'mesa-flexora': {
    name: 'Mesa flexora',
    slug: 'mesa-flexora',
    primaryMuscle: 'Posteriores de coxa',
    secondaryMuscles: ['Panturrilhas', 'Gluteos'],
    muscleGroups: ['Posteriores de coxa', 'Panturrilhas', 'Gluteos'],
    equipment: 'Maquina flexora',
    level: 'Iniciante',
    shortInstruction: 'Flexione os joelhos levando o rolo em direcao aos gluteos e retorne devagar.',
    commonMistakes: ['Levantar quadril', 'Usar impulso', 'Encurtar a descida'],
    safetyNote: 'Ajustar rolo acima do tornozelo e evitar compensar com lombar.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/mesa-flexora.gif',
  },
  afundo: {
    name: 'Afundo',
    slug: 'afundo',
    primaryMuscle: 'Quadriceps',
    secondaryMuscles: ['Gluteos', 'Posteriores', 'Core'],
    muscleGroups: ['Quadriceps', 'Gluteos', 'Posteriores', 'Core'],
    equipment: 'Peso corporal ou halteres',
    level: 'Intermediario',
    shortInstruction: 'De um passo a frente, desca em linha vertical e suba mantendo joelho alinhado.',
    commonMistakes: ['Inclinar tronco demais', 'Joelho entrar', 'Passo curto demais'],
    safetyNote: 'Comecar sem carga se houver instabilidade ou dor no joelho.',
    mediaStatus: 'placeholder',
    gif: null,
    futureGifPath: '/exercises/gifs/afundo.gif',
  },
  'desenvolvimento-halteres': {
    name: 'Desenvolvimento com halteres',
    slug: 'desenvolvimento-halteres',
    primaryMuscle: 'Ombros',
    secondaryMuscles: ['Triceps', 'Trapezio superior'],
    muscleGroups: ['Ombros', 'Triceps', 'Trapezio'],
    equipment: 'Halteres',
    level: 'Intermediario',
    shortInstruction: 'Empurre os halteres acima da cabeca mantendo punhos alinhados e tronco firme.',
    commonMistakes: ['Arquear lombar', 'Bater halteres', 'Descer abaixo do controle do ombro'],
    safetyNote: 'Evitar carga que force compensacao lombar.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/desenvolvimento-halteres.gif',
  },
  'elevacao-lateral': {
    name: 'Elevacao lateral',
    slug: 'elevacao-lateral',
    primaryMuscle: 'Ombros laterais',
    secondaryMuscles: ['Trapezio', 'Supraespinal'],
    muscleGroups: ['Ombros laterais', 'Trapezio'],
    equipment: 'Halteres ou polia',
    level: 'Iniciante',
    shortInstruction: 'Eleve os bracos ate a linha dos ombros com cotovelos levemente flexionados.',
    commonMistakes: ['Usar impulso', 'Elevar acima demais', 'Encolher ombros'],
    safetyNote: 'Usar carga baixa e ritmo controlado para proteger ombros.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/elevacao-lateral.gif',
  },
  'face-pull': {
    name: 'Face pull',
    slug: 'face-pull',
    primaryMuscle: 'Posterior de ombro',
    secondaryMuscles: ['Trapezio medio', 'Romboides', 'Rotadores externos'],
    muscleGroups: ['Posterior de ombro', 'Trapezio', 'Romboides'],
    equipment: 'Polia e corda',
    level: 'Intermediario',
    shortInstruction: 'Puxe a corda em direcao ao rosto abrindo cotovelos e aproximando escapulas.',
    commonMistakes: ['Puxar baixo demais', 'Projetar cabeca', 'Usar carga alta'],
    safetyNote: 'Priorizar controle e rotacao externa, nao carga.',
    mediaStatus: 'placeholder',
    gif: null,
    futureGifPath: '/exercises/gifs/face-pull.gif',
  },
  'rosca-direta': {
    name: 'Rosca direta',
    slug: 'rosca-direta',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Antebracos'],
    muscleGroups: ['Biceps', 'Antebracos'],
    equipment: 'Barra reta ou W',
    level: 'Iniciante',
    shortInstruction: 'Flexione os cotovelos levando a barra ate perto dos ombros sem balancar o tronco.',
    commonMistakes: ['Jogar o corpo', 'Abrir cotovelos', 'Descer sem controle'],
    safetyNote: 'Manter punhos neutros e reduzir carga se houver dor no cotovelo.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/rosca-direta.gif',
  },
  'rosca-martelo': {
    name: 'Rosca martelo',
    slug: 'rosca-martelo',
    primaryMuscle: 'Braquial',
    secondaryMuscles: ['Biceps', 'Antebracos'],
    muscleGroups: ['Braquial', 'Biceps', 'Antebracos'],
    equipment: 'Halteres',
    level: 'Iniciante',
    shortInstruction: 'Suba os halteres com pegada neutra mantendo cotovelos proximos ao corpo.',
    commonMistakes: ['Rodar punhos', 'Balancar tronco', 'Elevar ombros'],
    safetyNote: 'Evitar carga que puxe o ombro para frente.',
    mediaStatus: 'placeholder',
    gif: null,
    futureGifPath: '/exercises/gifs/rosca-martelo.gif',
  },
  'triceps-corda': {
    name: 'Triceps corda',
    slug: 'triceps-corda',
    primaryMuscle: 'Triceps',
    secondaryMuscles: ['Antebracos'],
    muscleGroups: ['Triceps', 'Antebracos'],
    equipment: 'Polia e corda',
    level: 'Iniciante',
    shortInstruction: 'Empurre a corda para baixo e abra levemente as pontas no final do movimento.',
    commonMistakes: ['Mexer cotovelos para frente', 'Inclinar demais', 'Subir sem controle'],
    safetyNote: 'Manter cotovelos estaveis e ombros relaxados.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/triceps-corda.gif',
  },
  prancha: {
    name: 'Prancha',
    slug: 'prancha',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Ombros', 'Gluteos'],
    muscleGroups: ['Core', 'Ombros', 'Gluteos'],
    equipment: 'Peso corporal',
    level: 'Iniciante',
    shortInstruction: 'Mantenha cotovelos abaixo dos ombros e corpo alinhado da cabeca aos pes.',
    commonMistakes: ['Quadril cair', 'Prender respiracao', 'Elevar demais o quadril'],
    safetyNote: 'Interromper se houver dor lombar e reduzir tempo de sustentacao.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/prancha.gif',
  },
  'abdominal-crunch': {
    name: 'Abdominal crunch',
    slug: 'abdominal-crunch',
    primaryMuscle: 'Reto abdominal',
    secondaryMuscles: ['Obliquos'],
    muscleGroups: ['Reto abdominal', 'Obliquos'],
    equipment: 'Peso corporal ou maquina',
    level: 'Iniciante',
    shortInstruction: 'Eleve o tronco curto contraindo o abdomen e retorne sem relaxar completamente.',
    commonMistakes: ['Puxar o pescoco', 'Subir demais', 'Fazer com impulso'],
    safetyNote: 'Manter pescoco neutro e movimento curto.',
    mediaStatus: 'needs_asset',
    gif: null,
    futureGifPath: '/exercises/gifs/abdominal-crunch.gif',
  },
};

const EXERCISE_ALIASES = {
  agachamento: 'agachamento-livre',
  supino: 'supino-reto',
  'supino-inclinado': 'supino-inclinado-halteres',
  flexao: 'flexao-bracos',
  puxada: 'puxada-alta',
  remada: 'remada-curvada',
  terra: 'levantamento-terra',
  desenvolvimento: 'desenvolvimento-halteres',
  elevacao: 'elevacao-lateral',
  rosca: 'rosca-direta',
  triceps: 'triceps-corda',
  abdominal: 'abdominal-crunch',
};

export function normalizeExerciseName(exerciseName) {
  return String(exerciseName || '')
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function getExerciseLabel(exercise) {
  if (exercise && typeof exercise === 'object') return exercise.name || exercise.mediaKey || '';
  return String(exercise || '');
}

export function getExerciseMedia(exercise) {
  const label = getExerciseLabel(exercise);
  const requestedKey = exercise && typeof exercise === 'object'
    ? exercise.mediaKey || exercise.name
    : exercise;
  const normalizedKey = normalizeExerciseName(requestedKey);
  const key = EXERCISE_ALIASES[normalizedKey] || normalizedKey;
  const mapped = EXERCISE_LIBRARY[key];

  if (mapped) {
    return {
      ...mapped,
      key,
      label: mapped.name,
      hasMedia: Boolean(mapped.gif),
    };
  }

  return {
    key,
    name: label || 'Exercicio',
    slug: key,
    label: label || 'Exercicio',
    gif: null,
    muscleGroups: [],
    primaryMuscle: null,
    secondaryMuscles: [],
    equipment: 'Livre',
    level: null,
    shortInstruction: 'Instrucao em breve.',
    commonMistakes: [],
    safetyNote: 'Use carga e amplitude confortaveis; procure orientacao profissional em caso de dor.',
    mediaStatus: 'placeholder',
    futureGifPath: null,
    hasMedia: false,
  };
}
