export const PERSONAL_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    studentLimit: 10,
    price: 24.9,
    priceNum: 24.9,
    priceLabel: 'R$ 24,90',
    priceDisplay: '24,90',
    description: 'Ideal para quem está começando.',
    popular: false,
    features: ['Até 10 alunos', 'Dashboard completo', 'Montagem de treinos', 'Suporte via E-mail'],
    iconColor: '#71717a',
    glowColor: 'rgba(113,113,122,0.12)',
    borderColor: 'rgba(113,113,122,0.25)',
    btnGradient: 'linear-gradient(135deg,#3f3f46,#52525b)',
    btnHoverGradient: 'linear-gradient(135deg,#52525b,#71717a)',
  },
  {
    id: 'pro',
    name: 'Pro',
    studentLimit: 30,
    price: 49.9,
    priceNum: 49.9,
    priceLabel: 'R$ 49,90',
    priceDisplay: '49,90',
    description: 'O equilíbrio perfeito entre IA e gestão.',
    popular: true,
    isPopular: true,
    features: ['Até 30 alunos', 'IA (20 treinos/mês)', 'Fotos antes/depois', 'Suporte Prioritário'],
    iconColor: '#3b82f6',
    glowColor: 'rgba(59,130,246,0.15)',
    borderColor: 'rgba(59,130,246,0.4)',
    btnGradient: 'linear-gradient(135deg,#2563eb,#3b82f6)',
    btnHoverGradient: 'linear-gradient(135deg,#1d4ed8,#2563eb)',
  },
  {
    id: 'elite',
    name: 'Elite',
    studentLimit: Infinity,
    price: 89.9,
    priceNum: 89.9,
    priceLabel: 'R$ 89,90',
    priceDisplay: '89,90',
    description: 'Domine o mercado sem limites.',
    popular: false,
    features: ['Alunos Ilimitados', 'IA Ilimitada (24/7)', 'Relatórios Avançados', 'Suporte VIP WhatsApp'],
    iconColor: '#f97316',
    glowColor: 'rgba(249,115,22,0.15)',
    borderColor: 'rgba(249,115,22,0.4)',
    btnGradient: 'linear-gradient(135deg,#ea580c,#f97316)',
    btnHoverGradient: 'linear-gradient(135deg,#c2410c,#ea580c)',
  },
];

export const STUDENT_PLANS = [
  { id: 'student-free', name: 'Aluno Free', price: 0, priceLabel: 'Grátis', features: ['Acesso aos treinos', 'Gráficos básicos', 'Histórico de fotos', 'Perfil do Aluno'] },
  { id: 'student-pro', name: 'Aluno Pro', price: 29.9, priceLabel: 'R$ 29,90', popular: true, features: ['IA Personal Trainer', 'Atlas Anatômico 3D', 'Gráficos de Evolução', 'Relatórios em PDF', 'Sem anúncios', 'Suporte Prioritário'] },
];
